from django.db import models
from django.utils.translation import ugettext_lazy as _

from facebook.fields import JSONField
from facebook.modules.base import Base
from facebook.modules.profile.user.models import User
from facebook.utils import warn_gone

class PostBase(Base):
    POST_TYPES = (('status', _('Status message')),
              ('link', _('Link')),
              ('photo', _('Photo')),
              ('video', _('Video')),
              ('note', _('Note')),
              )

    id = models.CharField(_('id'), max_length=40, primary_key=True)
    _from = models.ForeignKey(User, blank=True, null=True, verbose_name=_('from'),
                              related_name='%(app_label)s_%(class)s_posts_sent')
    # This field does not appear in the graph.
    _to = JSONField(_('to'), blank=True, null=True)  # could be M2M but nees JSON processor.
    _message = models.TextField(_('message'), blank=True)
    _message_tags = JSONField(_('message_tags'), blank=True, null=True, editable=False)
    _story = models.TextField(_('story'), blank=True,
        help_text="Text automatically generated by Facebook.")
    _picture = models.URLField(_('picture url'), max_length=255, blank=True)
    _link = models.URLField(_('link url'), max_length=255, blank=True)
    _name = models.CharField(_('link name'), max_length=255, blank=True)
    _caption = models.CharField(_('link caption'), max_length=255, blank=True)
    _description = models.TextField(_('link description'),null=True, blank=True)
    _source = models.URLField(_('movie source'), max_length=255, blank=True)
    _properties = JSONField(_('movie properties'), blank=True, null=True)
    _icon = models.URLField(_('icon'), blank=True)
    _actions = JSONField(_('actions'), blank=True, null=True)
    _privacy = JSONField(_('privacy'), blank=True, null=True)
    _type = models.CharField(_('type'), max_length=20, choices=POST_TYPES, default='status')
    _likes = JSONField(_('likes'), blank=True, null=True)
    _place = JSONField(_('place'), blank=True, null=True)
    _story_tags = JSONField(_('story tags'), blank=True, null=True, editable=False)
    _comments = JSONField(_('comments'), blank=True, null=True) #denormalized
    _object_id = models.BigIntegerField(_('object id'), blank=True, null=True)  #generic FK to image or movie
    _application = JSONField(_('application'), blank=True, null=True)
    _created_time = models.DateTimeField(_('created time'), blank=True, null=True)
    _updated_time = models.DateTimeField(_('updated time'), blank=True, null=True)
    _is_published = models.NullBooleanField(_('is published'), blank=True, null=True)

    class Meta(Base.Meta):
        abstract=True
        ordering = ['-_created_time']

    class Facebook:
        publish = 'feed'
        connections = {'likes': None, 'comments': None }  # TODO: Create models for reference
        arguments = ['message', 'picture', 'link', 'name', 'caption', 'description', 'source', 'actions']


    def __unicode__(self):
        return u'%s, %s %s' % (self.id, self._message[:50], self._picture)

    # Deal with changes from Facebook
    @property
    def _targeting(self):
        warn_gone('Post._targeting')
        return {}

    @property
    def _subject(self):
        warn_gone('Post._subject')
        return 'This field is deprecated and needs to be removed from your code.'

    # Note has no type attribute.
    def guess_type(self):
        if self._subject:
            self._type = 'note'
        elif self._story and self._picture:
            self._type = 'photo'
        elif not self._type:
            self._type = 'status'

    def get_from_facebook(self, graph=None, save=False, *args, **kwargs):
        super(PostBase, self).get_from_facebook(graph=graph, save=save, *args, **kwargs)
        self.guess_type()
        if save:
            self.save()

    def get_post_uid(self):
        ids = self.id.split('_')
        return ids[-1]

    @property
    def comments(self):
        return self._comments.get('data', [])

    @property
    def to(self):
        if hasattr(self._to, 'data'):
            return self._to.get('data')[0]
        else:
            return {'id': int(self.id.split('_')[0])}

    @property
    def actions(self):
        return dict((a['name'], a) for a in self._actions)

    @property
    def like_link(self):
        if self._link:
            return self._link
        elif self.actions.get('Like', False):
            return self.actions['Like']['link']
        elif self._type == 'note':
            return u'http://www.facebook.com/note.php?note_id=%s' % self.id
        else:
            try:
                return self.get_absolute_url()
            except AttributeError:
                return ''

    def status(self):
        if self._graph and 'id' in self._graph:
            return u'published'
        elif not self._graph:
            return u'not published'
        else:
            return u'error: %s' % self._graph


class Post(PostBase):
    class Meta(PostBase.Meta):
        app_label = 'facebook'
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        abstract = False

